# Generated by Django 5.1.3 on 2024-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/attachments'),
        ),
    ]
